// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b001_read_uid_after_cold_reset_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b001_read_uid_after_cold_reset_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B001";
    endfunction
endclass

class lvds_b002_write_to_uid_is_silently_ignored_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b002_write_to_uid_is_silently_ignored_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B002";
    endfunction
endclass

class lvds_b003_meta_page_0_returns_version_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b003_meta_page_0_returns_version_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B003";
    endfunction
endclass

class lvds_b004_meta_page_1_returns_date_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b004_meta_page_1_returns_date_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B004";
    endfunction
endclass

class lvds_b005_meta_page_2_returns_git_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b005_meta_page_2_returns_git_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B005";
    endfunction
endclass

class lvds_b006_meta_page_3_returns_instance_id_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b006_meta_page_3_returns_instance_id_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B006";
    endfunction
endclass

class lvds_b007_meta_invalid_page_selector_holds_last_valid_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b007_meta_invalid_page_selector_holds_last_valid_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B007";
    endfunction
endclass

class lvds_b008_capability_word_reports_compile_time_geometry_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b008_capability_word_reports_compile_time_geometry_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B008";
    endfunction
endclass

class lvds_b009_sync_pattern_reset_value_is_k28_5_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b009_sync_pattern_reset_value_is_k28_5_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B009";
    endfunction
endclass

class lvds_b010_sync_pattern_runtime_overwrite_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b010_sync_pattern_runtime_overwrite_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B010";
    endfunction
endclass

class lvds_b011_lane_go_reset_value_all_on_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b011_lane_go_reset_value_all_on_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B011";
    endfunction
endclass

class lvds_b012_lane_go_clear_stops_one_lane_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b012_lane_go_clear_stops_one_lane_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B012";
    endfunction
endclass

class lvds_b013_lane_go_all_clear_stops_every_lane_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b013_lane_go_all_clear_stops_every_lane_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B013";
    endfunction
endclass

class lvds_b014_dpa_hold_per_lane_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b014_dpa_hold_per_lane_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B014";
    endfunction
endclass

class lvds_b015_soft_reset_req_per_lane_self_clear_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b015_soft_reset_req_per_lane_self_clear_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B015";
    endfunction
endclass

class lvds_b016_mode_mask_bit_slip_legacy_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b016_mode_mask_bit_slip_legacy_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B016";
    endfunction
endclass

class lvds_b017_mode_mask_adaptive_eager_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b017_mode_mask_adaptive_eager_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B017";
    endfunction
endclass

class lvds_b018_mode_mask_auto_training_only_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b018_mode_mask_auto_training_only_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B018";
    endfunction
endclass

class lvds_b019_score_accept_clamp_on_out_of_range_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b019_score_accept_clamp_on_out_of_range_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B019";
    endfunction
endclass

class lvds_b020_score_reject_clamp_below_score_accept_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b020_score_reject_clamp_below_score_accept_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B020";
    endfunction
endclass

class lvds_b021_coe_ctrl_pllrst_asserted_out_of_cold_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b021_coe_ctrl_pllrst_asserted_out_of_cold_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B021";
    endfunction
endclass

class lvds_b022_dpa_training_released_after_coe_ctrl_plllock_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b022_dpa_training_released_after_coe_ctrl_plllock_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B022";
    endfunction
endclass

class lvds_b023_per_lane_dpa_lock_acquisition_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b023_per_lane_dpa_lock_acquisition_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B023";
    endfunction
endclass

class lvds_b024_fifo_reset_issued_after_dpa_lock_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b024_fifo_reset_issued_after_dpa_lock_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B024";
    endfunction
endclass

class lvds_b025_dpa_does_not_start_without_pll_lock_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b025_dpa_does_not_start_without_pll_lock_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B025";
    endfunction
endclass

class lvds_b026_control_reset_release_independent_of_data_reset_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b026_control_reset_release_independent_of_data_reset_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B026";
    endfunction
endclass

class lvds_b027_data_reset_release_independent_of_control_reset_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b027_data_reset_release_independent_of_control_reset_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B027";
    endfunction
endclass

class lvds_b028_cold_reset_returns_ip_to_defaults_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b028_cold_reset_returns_ip_to_defaults_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B028";
    endfunction
endclass

class lvds_b029_already_aligned_phase_0_k28_5_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b029_already_aligned_phase_0_k28_5_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B029";
    endfunction
endclass

class lvds_b030_phase_1_misalignment_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b030_phase_1_misalignment_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B030";
    endfunction
endclass

class lvds_b031_phase_2_misalignment_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b031_phase_2_misalignment_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B031";
    endfunction
endclass

class lvds_b032_phase_5_misalignment_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b032_phase_5_misalignment_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B032";
    endfunction
endclass

class lvds_b033_phase_9_misalignment_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b033_phase_9_misalignment_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B033";
    endfunction
endclass

class lvds_b034_phase_10_rollover_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b034_phase_10_rollover_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B034";
    endfunction
endclass

class lvds_b035_inverted_starting_rd_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b035_inverted_starting_rd_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B035";
    endfunction
endclass

class lvds_b036_4_lanes_all_phase_5_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b036_4_lanes_all_phase_5_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B036";
    endfunction
endclass

class lvds_b037_4_lanes_mixed_phases_1_3_5_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b037_4_lanes_mixed_phases_1_3_5_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B037";
    endfunction
endclass

class lvds_b038_n_lane_lanes_full_phase_sweep_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b038_n_lane_lanes_full_phase_sweep_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B038";
    endfunction
endclass

class lvds_b039_loss_sync_pattern_asserted_during_walk_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b039_loss_sync_pattern_asserted_during_walk_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B039";
    endfunction
endclass

class lvds_b040_loss_sync_pattern_cleared_after_lock_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b040_loss_sync_pattern_cleared_after_lock_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B040";
    endfunction
endclass

class lvds_b041_single_lane_training_to_engine_attach_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b041_single_lane_training_to_engine_attach_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B041";
    endfunction
endclass

class lvds_b042_single_lane_engine_release_after_sustained_accept_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b042_single_lane_engine_release_after_sustained_accept_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B042";
    endfunction
endclass

class lvds_b043_n_engine_1_reuse_cycle_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b043_n_engine_1_reuse_cycle_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B043";
    endfunction
endclass

class lvds_b044_n_engine_4_two_lanes_simultaneously_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b044_n_engine_4_two_lanes_simultaneously_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B044";
    endfunction
endclass

class lvds_b045_n_engine_n_lane_legacy_parity_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b045_n_engine_n_lane_legacy_parity_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B045";
    endfunction
endclass

class lvds_b046_lane_go_0_blocks_engine_attach_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b046_lane_go_0_blocks_engine_attach_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B046";
    endfunction
endclass

class lvds_b047_dpa_hold_defers_training_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b047_dpa_hold_defers_training_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B047";
    endfunction
endclass

class lvds_b048_mode_mask_bit_slip_never_invokes_engine_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b048_mode_mask_bit_slip_never_invokes_engine_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B048";
    endfunction
endclass

class lvds_b049_mode_mask_adaptive_invokes_engine_eagerly_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b049_mode_mask_adaptive_invokes_engine_eagerly_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B049";
    endfunction
endclass

class lvds_b050_mode_mask_auto_invokes_engine_only_on_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b050_mode_mask_auto_invokes_engine_only_on_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B050";
    endfunction
endclass

class lvds_b051_lane_select_atomic_over_10_reads_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b051_lane_select_atomic_over_10_reads_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B051";
    endfunction
endclass

class lvds_b052_lane_select_reset_default_0_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b052_lane_select_reset_default_0_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B052";
    endfunction
endclass

class lvds_b053_lane_select_change_between_reads_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b053_lane_select_change_between_reads_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B053";
    endfunction
endclass

class lvds_b054_lane_select_out_of_range_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b054_lane_select_out_of_range_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B054";
    endfunction
endclass

class lvds_b055_code_violations_increments_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b055_code_violations_increments_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B055";
    endfunction
endclass

class lvds_b056_disp_violations_increments_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b056_disp_violations_increments_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B056";
    endfunction
endclass

class lvds_b057_comma_losses_on_k28_5_dropout_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b057_comma_losses_on_k28_5_dropout_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B057";
    endfunction
endclass

class lvds_b058_bitslip_events_counts_pulses_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b058_bitslip_events_counts_pulses_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B058";
    endfunction
endclass

class lvds_b059_dpa_unlocks_on_dpalock_falling_edge_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b059_dpa_unlocks_on_dpalock_falling_edge_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B059";
    endfunction
endclass

class lvds_b060_realigns_on_phase_change_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b060_realigns_on_phase_change_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B060";
    endfunction
endclass

class lvds_b061_score_changes_on_engine_update_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b061_score_changes_on_engine_update_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B061";
    endfunction
endclass

class lvds_b062_engine_steerings_on_attach_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b062_engine_steerings_on_attach_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B062";
    endfunction
endclass

class lvds_b063_soft_resets_counts_requests_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b063_soft_resets_counts_requests_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B063";
    endfunction
endclass

class lvds_b064_uptime_since_lock_advances_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b064_uptime_since_lock_advances_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B064";
    endfunction
endclass

class lvds_b065_uptime_since_lock_resets_on_comma_loss_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b065_uptime_since_lock_resets_on_comma_loss_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B065";
    endfunction
endclass

class lvds_b066_two_counters_increment_same_cycle_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b066_two_counters_increment_same_cycle_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B066";
    endfunction
endclass

class lvds_b067_aperture_readback_equals_direct_csr_shadow_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b067_aperture_readback_equals_direct_csr_shadow_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B067";
    endfunction
endclass

class lvds_b068_all_counters_readable_on_every_enabled_lane_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b068_all_counters_readable_on_every_enabled_lane_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B068";
    endfunction
endclass

class lvds_b071_n_engine_1_n_lane_12_full_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b071_n_engine_1_n_lane_12_full_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B071";
    endfunction
endclass

class lvds_b072_n_engine_1_legacy_parity_falsifier_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b072_n_engine_1_legacy_parity_falsifier_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B072";
    endfunction
endclass

class lvds_b073_n_engine_n_lane_full_xbar_legacy_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b073_n_engine_n_lane_full_xbar_legacy_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B073";
    endfunction
endclass

class lvds_b074_n_engine_2_n_lane_12_full_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b074_n_engine_2_n_lane_12_full_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B074";
    endfunction
endclass

class lvds_b075_n_engine_4_butterfly_half_reachability_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b075_n_engine_4_butterfly_half_reachability_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B075";
    endfunction
endclass

class lvds_b076_n_engine_4_butterfly_quarter_reachability_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b076_n_engine_4_butterfly_quarter_reachability_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B076";
    endfunction
endclass

class lvds_b077_n_engine_4_nearest_k_reachability_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b077_n_engine_4_nearest_k_reachability_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B077";
    endfunction
endclass

class lvds_b078_engine_release_after_sustained_accept_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b078_engine_release_after_sustained_accept_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B078";
    endfunction
endclass

class lvds_b079_engine_reattach_on_glitch_after_release_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b079_engine_reattach_on_glitch_after_release_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B079";
    endfunction
endclass

class lvds_b080_engine_pool_full_occupancy_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_b080_engine_pool_full_occupancy_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "B080";
    endfunction
endclass

class lvds_e001_score_window_w_6_build_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e001_score_window_w_6_build_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E001";
    endfunction
endclass

class lvds_e002_score_window_w_16_build_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e002_score_window_w_16_build_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E002";
    endfunction
endclass

class lvds_e003_score_accept_score_window_w_must_be_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e003_score_accept_score_window_w_must_be_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E003";
    endfunction
endclass

class lvds_e004_score_accept_1_one_bit_accept_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e004_score_accept_1_one_bit_accept_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E004";
    endfunction
endclass

class lvds_e005_score_reject_0_always_rejects_below_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e005_score_reject_0_always_rejects_below_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E005";
    endfunction
endclass

class lvds_e006_score_tie_between_two_phases_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e006_score_tie_between_two_phases_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E006";
    endfunction
endclass

class lvds_e007_score_tie_between_three_phases_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e007_score_tie_between_three_phases_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E007";
    endfunction
endclass

class lvds_e008_alternating_accept_reject_crossing_threshold_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e008_alternating_accept_reject_crossing_threshold_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E008";
    endfunction
endclass

class lvds_e009_one_bit_error_inside_score_window_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e009_one_bit_error_inside_score_window_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E009";
    endfunction
endclass

class lvds_e010_perfect_100_score_window_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e010_perfect_100_score_window_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E010";
    endfunction
endclass

class lvds_e011_bitslip_walk_off_10_pulses_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e011_bitslip_walk_off_10_pulses_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E011";
    endfunction
endclass

class lvds_e012_bitslip_walk_attempted_during_dpa_hold_1_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e012_bitslip_walk_attempted_during_dpa_hold_1_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E012";
    endfunction
endclass

class lvds_e013_back_to_back_bitslip_pulses_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e013_back_to_back_bitslip_pulses_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E013";
    endfunction
endclass

class lvds_e014_bitslip_walk_on_attached_engine_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e014_bitslip_walk_on_attached_engine_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E014";
    endfunction
endclass

class lvds_e015_walk_on_lane_0_while_lane_1_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e015_walk_on_lane_0_while_lane_1_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E015";
    endfunction
endclass

class lvds_e016_bitslip_walk_during_pll_relock_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e016_bitslip_walk_during_pll_relock_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E016";
    endfunction
endclass

class lvds_e017_rollover_at_non_multiple_of_10_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e017_rollover_at_non_multiple_of_10_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E017";
    endfunction
endclass

class lvds_e018_n_engine_1_glitch_on_2_lanes_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e018_n_engine_1_glitch_on_2_lanes_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E018";
    endfunction
endclass

class lvds_e019_n_engine_1_glitch_on_4_lanes_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e019_n_engine_1_glitch_on_4_lanes_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E019";
    endfunction
endclass

class lvds_e020_n_engine_1_glitch_on_12_lanes_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e020_n_engine_1_glitch_on_12_lanes_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E020";
    endfunction
endclass

class lvds_e021_n_engine_2_glitch_on_4_lanes_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e021_n_engine_2_glitch_on_4_lanes_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E021";
    endfunction
endclass

class lvds_e022_engine_preempted_by_lock_loss_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e022_engine_preempted_by_lock_loss_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E022";
    endfunction
endclass

class lvds_e023_engine_attached_lane_goes_idle_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e023_engine_attached_lane_goes_idle_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E023";
    endfunction
endclass

class lvds_e024_butterfly_half_lane_outside_reachable_subset_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e024_butterfly_half_lane_outside_reachable_subset_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E024";
    endfunction
endclass

class lvds_e025_butterfly_quarter_lane_outside_any_free_engine_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e025_butterfly_quarter_lane_outside_any_free_engine_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E025";
    endfunction
endclass

class lvds_e026_nearest_k_boundary_lane_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e026_nearest_k_boundary_lane_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E026";
    endfunction
endclass

class lvds_e027_topology_change_at_runtime_rejected_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e027_topology_change_at_runtime_rejected_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E027";
    endfunction
endclass

class lvds_e028_fabric_one_hot_exclusivity_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e028_fabric_one_hot_exclusivity_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E028";
    endfunction
endclass

class lvds_e029_lane_select_change_mid_read_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e029_lane_select_change_mid_read_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E029";
    endfunction
endclass

class lvds_e030_lane_select_large_value_clamp_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e030_lane_select_large_value_clamp_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E030";
    endfunction
endclass

class lvds_e031_concurrent_counter_increment_during_aperture_read_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e031_concurrent_counter_increment_during_aperture_read_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E031";
    endfunction
endclass

class lvds_e032_capability_word_write_attempt_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e032_capability_word_write_attempt_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E032";
    endfunction
endclass

class lvds_e033_aperture_word_out_of_range_read_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e033_aperture_word_out_of_range_read_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E033";
    endfunction
endclass

class lvds_e034_reserved_csr_word_read_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e034_reserved_csr_word_read_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E034";
    endfunction
endclass

class lvds_e035_reserved_csr_word_write_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e035_reserved_csr_word_write_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E035";
    endfunction
endclass

class lvds_e036_csr_write_while_soft_reset_req_0_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e036_csr_write_while_soft_reset_req_0_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E036";
    endfunction
endclass

class lvds_e037_back_to_back_csr_writes_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e037_back_to_back_csr_writes_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E037";
    endfunction
endclass

class lvds_e038_read_modify_write_of_mode_mask_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e038_read_modify_write_of_mode_mask_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E038";
    endfunction
endclass

class lvds_e039_csr_access_at_maximum_address_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e039_csr_access_at_maximum_address_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E039";
    endfunction
endclass

class lvds_e040_csr_access_above_maximum_address_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e040_csr_access_above_maximum_address_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E040";
    endfunction
endclass

class lvds_e041_bitslip_walk_lane_0_vs_lane_1_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e041_bitslip_walk_lane_0_vs_lane_1_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E041";
    endfunction
endclass

class lvds_e042_glitch_on_lane_5_vs_lane_6_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e042_glitch_on_lane_5_vs_lane_6_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E042";
    endfunction
endclass

class lvds_e043_soft_reset_lane_3_vs_lane_4_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e043_soft_reset_lane_3_vs_lane_4_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E043";
    endfunction
endclass

class lvds_e044_dpa_unlock_pulse_lane_2_vs_engine_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e044_dpa_unlock_pulse_lane_2_vs_engine_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E044";
    endfunction
endclass

class lvds_e045_sync_pattern_change_resets_all_lanes_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e045_sync_pattern_change_resets_all_lanes_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E045";
    endfunction
endclass

class lvds_e046_sync_pattern_k28_0_lock_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e046_sync_pattern_k28_0_lock_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E046";
    endfunction
endclass

class lvds_e047_sync_pattern_k23_7_lock_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e047_sync_pattern_k23_7_lock_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E047";
    endfunction
endclass

class lvds_e048_sync_pattern_with_wrong_rd_start_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e048_sync_pattern_with_wrong_rd_start_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E048";
    endfunction
endclass

class lvds_e049_sync_pattern_transient_change_during_traffic_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e049_sync_pattern_transient_change_during_traffic_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E049";
    endfunction
endclass

class lvds_e050_illegal_sync_pattern_all_zero_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_e050_illegal_sync_pattern_all_zero_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "E050";
    endfunction
endclass

class lvds_p001_100k_k28_5_idle_no_glitch_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p001_100k_k28_5_idle_no_glitch_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P001";
    endfunction
endclass

class lvds_p002_100k_symbols_1_glitch_on_all_lanes_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p002_100k_symbols_1_glitch_on_all_lanes_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P002";
    endfunction
endclass

class lvds_p003_100k_symbols_contention_sweep_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p003_100k_symbols_contention_sweep_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P003";
    endfunction
endclass

class lvds_p004_1m_symbols_0_1_glitch_rate_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p004_1m_symbols_0_1_glitch_rate_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P004";
    endfunction
endclass

class lvds_p005_1m_symbols_1_glitch_rate_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p005_1m_symbols_1_glitch_rate_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P005";
    endfunction
endclass

class lvds_p006_worst_case_steering_latency_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p006_worst_case_steering_latency_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P006";
    endfunction
endclass

class lvds_p007_mixed_framed_traffic_glitches_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p007_mixed_framed_traffic_glitches_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P007";
    endfunction
endclass

class lvds_p008_100m_symbol_k28_5_line_rate_sustainment_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p008_100m_symbol_k28_5_line_rate_sustainment_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P008";
    endfunction
endclass

class lvds_p009_random_sync_pattern_transient_changes_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p009_random_sync_pattern_transient_changes_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P009";
    endfunction
endclass

class lvds_p010_random_soft_resets_during_soak_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p010_random_soft_resets_during_soak_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P010";
    endfunction
endclass

class lvds_p011_1m_cycle_line_rate_sustainment_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p011_1m_cycle_line_rate_sustainment_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P011";
    endfunction
endclass

class lvds_p012_50_random_backpressure_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p012_50_random_backpressure_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P012";
    endfunction
endclass

class lvds_p013_burst_stalls_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p013_burst_stalls_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P013";
    endfunction
endclass

class lvds_p014_permanent_backpressure_on_one_lane_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p014_permanent_backpressure_on_one_lane_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P014";
    endfunction
endclass

class lvds_p015_mixed_ready_patterns_per_lane_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p015_mixed_ready_patterns_per_lane_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P015";
    endfunction
endclass

class lvds_p016_throughput_with_engine_churn_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p016_throughput_with_engine_churn_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P016";
    endfunction
endclass

class lvds_p017_throughput_with_periodic_dpa_unlock_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p017_throughput_with_periodic_dpa_unlock_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P017";
    endfunction
endclass

class lvds_p018_throughput_with_sync_pattern_flips_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p018_throughput_with_sync_pattern_flips_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P018";
    endfunction
endclass

class lvds_p019_minimum_lane_count_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p019_minimum_lane_count_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P019";
    endfunction
endclass

class lvds_p020_maximum_lane_count_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p020_maximum_lane_count_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P020";
    endfunction
endclass

class lvds_p021_code_violations_saturates_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p021_code_violations_saturates_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P021";
    endfunction
endclass

class lvds_p022_disp_violations_saturates_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p022_disp_violations_saturates_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P022";
    endfunction
endclass

class lvds_p023_bitslip_events_saturates_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p023_bitslip_events_saturates_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P023";
    endfunction
endclass

class lvds_p024_uptime_since_lock_saturates_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p024_uptime_since_lock_saturates_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P024";
    endfunction
endclass

class lvds_p025_checkpoint_growth_idle_soak_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p025_checkpoint_growth_idle_soak_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P025";
    endfunction
endclass

class lvds_p026_no_phantom_error_events_under_idle_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p026_no_phantom_error_events_under_idle_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P026";
    endfunction
endclass

class lvds_p027_no_phantom_engine_steerings_under_idle_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p027_no_phantom_engine_steerings_under_idle_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P027";
    endfunction
endclass

class lvds_p028_periodic_counter_readback_during_idle_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p028_periodic_counter_readback_during_idle_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P028";
    endfunction
endclass

class lvds_p029_periodic_soft_reset_during_idle_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p029_periodic_soft_reset_during_idle_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P029";
    endfunction
endclass

class lvds_p030_pll_lock_churn_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p030_pll_lock_churn_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P030";
    endfunction
endclass

class lvds_p031_random_glitch_class_per_cycle_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p031_random_glitch_class_per_cycle_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P031";
    endfunction
endclass

class lvds_p032_random_lane_targeting_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p032_random_lane_targeting_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P032";
    endfunction
endclass

class lvds_p033_random_engine_attach_delay_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p033_random_engine_attach_delay_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P033";
    endfunction
endclass

class lvds_p034_random_score_window_changes_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p034_random_score_window_changes_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P034";
    endfunction
endclass

class lvds_p035_random_sync_pattern_changes_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p035_random_sync_pattern_changes_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P035";
    endfunction
endclass

class lvds_p036_random_mode_mask_flips_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p036_random_mode_mask_flips_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P036";
    endfunction
endclass

class lvds_p037_random_build_matrix_sweep_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p037_random_build_matrix_sweep_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P037";
    endfunction
endclass

class lvds_p038_random_lane_select_cadence_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p038_random_lane_select_cadence_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P038";
    endfunction
endclass

class lvds_p039_random_soft_reset_cadence_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p039_random_soft_reset_cadence_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P039";
    endfunction
endclass

class lvds_p040_1g_cycle_mixed_random_workload_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_p040_1g_cycle_mixed_random_workload_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "P040";
    endfunction
endclass

class lvds_x001_soft_reset_clears_that_lane_s_counters_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x001_soft_reset_clears_that_lane_s_counters_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X001";
    endfunction
endclass

class lvds_x002_soft_reset_during_steering_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x002_soft_reset_during_steering_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X002";
    endfunction
endclass

class lvds_x003_soft_reset_during_bitslip_walk_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x003_soft_reset_during_bitslip_walk_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X003";
    endfunction
endclass

class lvds_x004_soft_reset_during_dpa_unlock_event_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x004_soft_reset_during_dpa_unlock_event_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X004";
    endfunction
endclass

class lvds_x005_all_lanes_soft_reset_simultaneously_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x005_all_lanes_soft_reset_simultaneously_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X005";
    endfunction
endclass

class lvds_x006_self_clear_after_idle_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x006_self_clear_after_idle_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X006";
    endfunction
endclass

class lvds_x007_soft_reset_on_disabled_lane_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x007_soft_reset_on_disabled_lane_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X007";
    endfunction
endclass

class lvds_x008_back_to_back_soft_reset_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x008_back_to_back_soft_reset_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X008";
    endfunction
endclass

class lvds_x009_stuck_high_0x3ff_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x009_stuck_high_0x3ff_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X009";
    endfunction
endclass

class lvds_x010_stuck_low_0x000_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x010_stuck_low_0x000_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X010";
    endfunction
endclass

class lvds_x011_stuck_on_one_valid_non_k28_5_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x011_stuck_on_one_valid_non_k28_5_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X011";
    endfunction
endclass

class lvds_x012_bouncing_50_high_low_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x012_bouncing_50_high_low_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X012";
    endfunction
endclass

class lvds_x013_random_data_only_no_k28_5_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x013_random_data_only_no_k28_5_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X013";
    endfunction
endclass

class lvds_x014_sparse_sync_k28_5_every_1024_symbols_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x014_sparse_sync_k28_5_every_1024_symbols_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X014";
    endfunction
endclass

class lvds_x015_dpalock_never_asserts_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x015_dpalock_never_asserts_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X015";
    endfunction
endclass

class lvds_x016_rollover_without_bitslip_request_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x016_rollover_without_bitslip_request_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X016";
    endfunction
endclass

class lvds_x017_redriver_losn_0_on_lane_0_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x017_redriver_losn_0_on_lane_0_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X017";
    endfunction
endclass

class lvds_x018_redriver_losn_1_baseline_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x018_redriver_losn_1_baseline_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X018";
    endfunction
endclass

class lvds_x019_continuous_bitslip_churn_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x019_continuous_bitslip_churn_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X019";
    endfunction
endclass

class lvds_x020_pll_drops_lock_mid_traffic_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x020_pll_drops_lock_mid_traffic_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X020";
    endfunction
endclass

class lvds_x021_dpalock_asserts_then_drops_every_100_cycles_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x021_dpalock_asserts_then_drops_every_100_cycles_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X021";
    endfunction
endclass

class lvds_x022_dparst_held_too_long_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x022_dparst_held_too_long_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X022";
    endfunction
endclass

class lvds_x023_fiforst_handshake_never_completes_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x023_fiforst_handshake_never_completes_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X023";
    endfunction
endclass

class lvds_x024_spurious_rollover_without_bitslip_request_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x024_spurious_rollover_without_bitslip_request_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X024";
    endfunction
endclass

class lvds_x025_csr_write_while_soft_reset_req_in_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x025_csr_write_while_soft_reset_req_in_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X025";
    endfunction
endclass

class lvds_x026_csr_write_during_control_reset_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x026_csr_write_during_control_reset_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X026";
    endfunction
endclass

class lvds_x027_csr_read_during_control_reset_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x027_csr_read_during_control_reset_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X027";
    endfunction
endclass

class lvds_x028_write_to_read_only_words_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x028_write_to_read_only_words_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X028";
    endfunction
endclass

class lvds_x029_lane_go_write_with_extra_bits_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x029_lane_go_write_with_extra_bits_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X029";
    endfunction
endclass

class lvds_x030_dpa_hold_write_with_extra_bits_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x030_dpa_hold_write_with_extra_bits_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X030";
    endfunction
endclass

class lvds_x031_lane_select_write_with_all_set_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x031_lane_select_write_with_all_set_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X031";
    endfunction
endclass

class lvds_x032_score_accept_0_illegal_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x032_score_accept_0_illegal_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X032";
    endfunction
endclass

class lvds_x033_mode_mask_reserved_value_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x033_mode_mask_reserved_value_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X033";
    endfunction
endclass

class lvds_x034_csr_access_at_non_existent_address_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x034_csr_access_at_non_existent_address_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X034";
    endfunction
endclass

class lvds_x035_sva_routing_excl_liveness_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x035_sva_routing_excl_liveness_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X035";
    endfunction
endclass

class lvds_x036_sva_counter_sat_liveness_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x036_sva_counter_sat_liveness_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X036";
    endfunction
endclass

class lvds_x037_sva_avalon_st_liveness_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x037_sva_avalon_st_liveness_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X037";
    endfunction
endclass

class lvds_x038_sva_avalon_mm_liveness_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x038_sva_avalon_mm_liveness_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X038";
    endfunction
endclass

class lvds_x039_sva_csr_aperture_liveness_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x039_sva_csr_aperture_liveness_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X039";
    endfunction
endclass

class lvds_x040_sva_engine_attach_liveness_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x040_sva_engine_attach_liveness_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X040";
    endfunction
endclass

class lvds_x041_sva_train_fsm_liveness_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x041_sva_train_fsm_liveness_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X041";
    endfunction
endclass

class lvds_x042_both_resets_asserted_then_released_same_cycle_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x042_both_resets_asserted_then_released_same_cycle_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X042";
    endfunction
endclass

class lvds_x043_control_reset_deassert_before_data_reset_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x043_control_reset_deassert_before_data_reset_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X043";
    endfunction
endclass

class lvds_x044_data_reset_deassert_before_control_reset_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x044_data_reset_deassert_before_control_reset_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X044";
    endfunction
endclass

class lvds_x045_reset_asserted_during_csr_write_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x045_reset_asserted_during_csr_write_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X045";
    endfunction
endclass

class lvds_x046_reset_asserted_during_avst_handshake_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x046_reset_asserted_during_avst_handshake_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X046";
    endfunction
endclass

class lvds_x047_reset_asserted_during_engine_attach_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x047_reset_asserted_during_engine_attach_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X047";
    endfunction
endclass

class lvds_x048_reset_asserted_during_bitslip_walk_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x048_reset_asserted_during_bitslip_walk_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X048";
    endfunction
endclass

class lvds_x049_reset_asserted_during_dpa_training_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x049_reset_asserted_during_dpa_training_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X049";
    endfunction
endclass

class lvds_x050_reset_glitch_1_cycle_pulse_test extends lvds_case_test_base;
    `uvm_component_utils(lvds_x050_reset_glitch_1_cycle_pulse_test)

    function new(string name, uvm_component parent);
        super.new(name, parent);
        default_case_id = "X050";
    endfunction
endclass
