#!/usr/bin/env python3
"""Generate LVDS UVM case sequences from DV bucket Markdown tables."""

from __future__ import annotations

import pathlib
import re
import textwrap
import unicodedata


ROOT = pathlib.Path(__file__).resolve().parents[2]
DOCS = ROOT / "doc"
UVM = ROOT / "uvm"
SEQ = UVM / "sequence"
TESTS = UVM / "tests"

BUCKETS = [
    ("B", "LVDS_BUCKET_BASIC", "tb/doc/DV_BASIC.md"),
    ("E", "LVDS_BUCKET_EDGE", "tb/doc/DV_EDGE.md"),
    ("P", "LVDS_BUCKET_PROF", "tb/doc/DV_PROF.md"),
    ("X", "LVDS_BUCKET_ERROR", "tb/doc/DV_ERROR.md"),
]

SKIP_CONTINUOUS = {"E028", "E040", "P025", "X035", "X036", "X037", "X038", "X039", "X040", "X041"}


def ascii_text(value: str) -> str:
    replacements = {
        "\u2192": "->",
        "\u2190": "<-",
        "\u2265": ">=",
        "\u2264": "<=",
        "\u00b1": "+/-",
        "\u2248": "~",
        "\u00d7": "x",
        "\u00a7": "section ",
        "\u2014": "-",
        "\u2013": "-",
        "\u201c": '"',
        "\u201d": '"',
        "\u2019": "'",
        "\u221e": "inf",
    }
    for src, dst in replacements.items():
        value = value.replace(src, dst)
    value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    return re.sub(r"\s+", " ", value).strip()


def sv_string(value: str) -> str:
    value = ascii_text(value)
    return value.replace("\\", "\\\\").replace('"', '\\"')


def slug(value: str, max_words: int = 7) -> str:
    value = ascii_text(value).lower()
    value = re.sub(r"`([^`]*)`", r"\1", value)
    words = re.findall(r"[a-z0-9]+", value)
    if not words:
        return "case"
    return "_".join(words[:max_words])


def parse_cases() -> list[dict[str, object]]:
    cases: list[dict[str, object]] = []
    line_re = re.compile(
        r"^\|\s*([BEOPX]\d{3})\s*\|\s*([DR])\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|\s*(.*?)\s*\|"
    )
    for prefix, bucket_enum, rel_path in BUCKETS:
        path = ROOT.parents[0] / rel_path
        if not path.exists():
            path = DOCS / pathlib.Path(rel_path).name
        for line in path.read_text(encoding="utf-8").splitlines():
            match = line_re.match(line)
            if not match:
                continue
            case_id, method, scenario, iterations, stimulus, pass_criteria = match.groups()
            number = int(case_id[1:])
            iter_match = re.search(r"\d+", iterations)
            iter_count = int(iter_match.group(0)) if iter_match else 1
            method_enum = "LVDS_METHOD_RANDOM" if method == "R" else "LVDS_METHOD_DIRECTED"
            cases.append(
                {
                    "id": case_id,
                    "prefix": prefix,
                    "bucket_enum": bucket_enum,
                    "method_enum": method_enum,
                    "method": method,
                    "number": number,
                    "iterations": iter_count,
                    "scenario": ascii_text(scenario),
                    "stimulus": ascii_text(stimulus),
                    "pass": ascii_text(pass_criteria),
                    "class_slug": slug(scenario),
                    "expect_sva": case_id == "E028" or (case_id.startswith("X") and 35 <= number <= 41),
                }
            )
    seen = set()
    for case in cases:
        if case["id"] in seen:
            raise SystemExit(f"duplicate case id {case['id']}")
        seen.add(case["id"])
    return cases


def class_name(case: dict[str, object], suffix: str) -> str:
    return f"lvds_{str(case['id']).lower()}_{case['class_slug']}_{suffix}"


def write_catalog(cases: list[dict[str, object]]) -> None:
    lines: list[str] = []
    lines.append("// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.\n")
    lines.append("function automatic lvds_case_desc_t lvds_get_case_desc(input string case_id);\n")
    lines.append("    lvds_case_desc_t desc;\n")
    lines.append("    desc.id = \"\";\n")
    lines.append("    unique case (case_id)\n")
    for case in cases:
        lines.append(f"        \"{case['id']}\": begin\n")
        lines.append(f"            desc.id = \"{case['id']}\";\n")
        lines.append(f"            desc.bucket = {case['bucket_enum']};\n")
        lines.append(f"            desc.method = {case['method_enum']};\n")
        lines.append(f"            desc.group = lvds_group_from_id(\"{case['id']}\");\n")
        lines.append(f"            desc.case_num = {case['number']};\n")
        lines.append(f"            desc.iterations = {case['iterations']};\n")
        lines.append(f"            desc.scenario = \"{sv_string(str(case['scenario']))}\";\n")
        lines.append(f"            desc.stimulus = \"{sv_string(str(case['stimulus']))}\";\n")
        lines.append(f"            desc.pass_criteria = \"{sv_string(str(case['pass']))}\";\n")
        lines.append(f"            desc.expect_sva_failure = {1 if case['expect_sva'] else 0};\n")
        lines.append("        end\n")
    lines.append("        default: begin end\n")
    lines.append("    endcase\n")
    lines.append("    return desc;\n")
    lines.append("endfunction\n\n")

    lines.append("function automatic int lvds_case_count();\n")
    lines.append(f"    return {len(cases)};\n")
    lines.append("endfunction\n\n")

    lines.append("function automatic string lvds_case_id_at(input int index);\n")
    lines.append("    unique case (index)\n")
    for idx, case in enumerate(cases):
        lines.append(f"        {idx}: return \"{case['id']}\";\n")
    lines.append("        default: return \"\";\n")
    lines.append("    endcase\n")
    lines.append("endfunction\n\n")

    lines.append("function automatic int lvds_bucket_case_count(input lvds_bucket_e bucket);\n")
    lines.append("    unique case (bucket)\n")
    for _, bucket_enum, _ in BUCKETS:
        count = sum(1 for case in cases if case["bucket_enum"] == bucket_enum)
        lines.append(f"        {bucket_enum}: return {count};\n")
    lines.append("        default: return 0;\n")
    lines.append("    endcase\n")
    lines.append("endfunction\n\n")

    lines.append("function automatic string lvds_bucket_case_id_at(input lvds_bucket_e bucket, input int index);\n")
    lines.append("    unique case (bucket)\n")
    for _, bucket_enum, _ in BUCKETS:
        bucket_cases = [case for case in cases if case["bucket_enum"] == bucket_enum]
        lines.append(f"        {bucket_enum}: begin\n")
        lines.append("            unique case (index)\n")
        for idx, case in enumerate(bucket_cases):
            lines.append(f"                {idx}: return \"{case['id']}\";\n")
        lines.append("                default: return \"\";\n")
        lines.append("            endcase\n")
        lines.append("        end\n")
    lines.append("        default: return \"\";\n")
    lines.append("    endcase\n")
    lines.append("endfunction\n\n")

    lines.append("function automatic bit lvds_skip_in_continuous_frame(input string case_id);\n")
    lines.append("    unique case (case_id)\n")
    for case_id in sorted(SKIP_CONTINUOUS):
        lines.append(f"        \"{case_id}\": return 1'b1;\n")
    lines.append("        default: return 1'b0;\n")
    lines.append("    endcase\n")
    lines.append("endfunction\n")

    (SEQ / "lvds_case_catalog.svh").write_text("".join(lines), encoding="ascii")


def write_sequences(cases: list[dict[str, object]]) -> None:
    include_lines = ["// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.\n"]
    for case in cases:
        seq_name = class_name(case, "seq")
        file_name = f"{seq_name}.sv"
        include_lines.append(f"`include \"{file_name}\"\n")
        body = f"""\
// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class {seq_name} extends lvds_case_sequence_base;
    `uvm_object_utils({seq_name})

    function new(string name = "{seq_name}");
        super.new(name);
        case_id = "{case['id']}";
    endfunction
endclass
"""
        (SEQ / file_name).write_text(body, encoding="ascii")
    (SEQ / "lvds_case_sequence_list.svh").write_text("".join(include_lines), encoding="ascii")


def write_tests(cases: list[dict[str, object]]) -> None:
    lines = ["// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.\n"]
    for case in cases:
        test_name = class_name(case, "test")
        lines.append(
            textwrap.dedent(
                f"""\
                class {test_name} extends lvds_case_test_base;
                    `uvm_component_utils({test_name})

                    function new(string name, uvm_component parent);
                        super.new(name, parent);
                        default_case_id = "{case['id']}";
                    endfunction
                endclass

                """
            )
        )
    (TESTS / "lvds_case_tests.svh").write_text("".join(lines).rstrip() + "\n", encoding="ascii")


def write_lists(cases: list[dict[str, object]]) -> None:
    (UVM / "regression_cases.list").write_text("\n".join(str(case["id"]) for case in cases) + "\n", encoding="ascii")
    for prefix, bucket_enum, _ in BUCKETS:
        bucket_cases = [str(case["id"]) for case in cases if case["bucket_enum"] == bucket_enum]
        (UVM / f"regression_{prefix.lower()}.list").write_text("\n".join(bucket_cases) + "\n", encoding="ascii")


def main() -> None:
    SEQ.mkdir(parents=True, exist_ok=True)
    TESTS.mkdir(parents=True, exist_ok=True)
    cases = parse_cases()
    write_catalog(cases)
    write_sequences(cases)
    write_tests(cases)
    write_lists(cases)
    print(f"generated {len(cases)} LVDS UVM case sequences")


if __name__ == "__main__":
    main()
