// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b005_meta_page_2_returns_git_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b005_meta_page_2_returns_git_seq)

    function new(string name = "lvds_b005_meta_page_2_returns_git_seq");
        super.new(name);
        case_id = "B005";
    endfunction
endclass
