// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e027_topology_change_at_runtime_rejected_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e027_topology_change_at_runtime_rejected_seq)

    function new(string name = "lvds_e027_topology_change_at_runtime_rejected_seq");
        super.new(name);
        case_id = "E027";
    endfunction
endclass
