// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b057_comma_losses_on_k28_5_dropout_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b057_comma_losses_on_k28_5_dropout_seq)

    function new(string name = "lvds_b057_comma_losses_on_k28_5_dropout_seq");
        super.new(name);
        case_id = "B057";
    endfunction
endclass
