// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e032_capability_word_write_attempt_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e032_capability_word_write_attempt_seq)

    function new(string name = "lvds_e032_capability_word_write_attempt_seq");
        super.new(name);
        case_id = "E032";
    endfunction
endclass
