// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b022_dpa_training_released_after_coe_ctrl_plllock_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b022_dpa_training_released_after_coe_ctrl_plllock_seq)

    function new(string name = "lvds_b022_dpa_training_released_after_coe_ctrl_plllock_seq");
        super.new(name);
        case_id = "B022";
    endfunction
endclass
