// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b043_n_engine_1_reuse_cycle_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b043_n_engine_1_reuse_cycle_seq)

    function new(string name = "lvds_b043_n_engine_1_reuse_cycle_seq");
        super.new(name);
        case_id = "B043";
    endfunction
endclass
