// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b079_engine_reattach_on_glitch_after_release_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b079_engine_reattach_on_glitch_after_release_seq)

    function new(string name = "lvds_b079_engine_reattach_on_glitch_after_release_seq");
        super.new(name);
        case_id = "B079";
    endfunction
endclass
