// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x022_dparst_held_too_long_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x022_dparst_held_too_long_seq)

    function new(string name = "lvds_x022_dparst_held_too_long_seq");
        super.new(name);
        case_id = "X022";
    endfunction
endclass
