// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x047_reset_asserted_during_engine_attach_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x047_reset_asserted_during_engine_attach_seq)

    function new(string name = "lvds_x047_reset_asserted_during_engine_attach_seq");
        super.new(name);
        case_id = "X047";
    endfunction
endclass
