// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b053_lane_select_change_between_reads_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b053_lane_select_change_between_reads_seq)

    function new(string name = "lvds_b053_lane_select_change_between_reads_seq");
        super.new(name);
        case_id = "B053";
    endfunction
endclass
