// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p013_burst_stalls_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p013_burst_stalls_seq)

    function new(string name = "lvds_p013_burst_stalls_seq");
        super.new(name);
        case_id = "P013";
    endfunction
endclass
