// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b055_code_violations_increments_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b055_code_violations_increments_seq)

    function new(string name = "lvds_b055_code_violations_increments_seq");
        super.new(name);
        case_id = "B055";
    endfunction
endclass
