// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p034_random_score_window_changes_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p034_random_score_window_changes_seq)

    function new(string name = "lvds_p034_random_score_window_changes_seq");
        super.new(name);
        case_id = "P034";
    endfunction
endclass
