// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p005_1m_symbols_1_glitch_rate_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p005_1m_symbols_1_glitch_rate_seq)

    function new(string name = "lvds_p005_1m_symbols_1_glitch_rate_seq");
        super.new(name);
        case_id = "P005";
    endfunction
endclass
