// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p040_1g_cycle_mixed_random_workload_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p040_1g_cycle_mixed_random_workload_seq)

    function new(string name = "lvds_p040_1g_cycle_mixed_random_workload_seq");
        super.new(name);
        case_id = "P040";
    endfunction
endclass
