// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x040_sva_engine_attach_liveness_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x040_sva_engine_attach_liveness_seq)

    function new(string name = "lvds_x040_sva_engine_attach_liveness_seq");
        super.new(name);
        case_id = "X040";
    endfunction
endclass
