// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x049_reset_asserted_during_dpa_training_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x049_reset_asserted_during_dpa_training_seq)

    function new(string name = "lvds_x049_reset_asserted_during_dpa_training_seq");
        super.new(name);
        case_id = "X049";
    endfunction
endclass
