// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e022_engine_preempted_by_lock_loss_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e022_engine_preempted_by_lock_loss_seq)

    function new(string name = "lvds_e022_engine_preempted_by_lock_loss_seq");
        super.new(name);
        case_id = "E022";
    endfunction
endclass
