// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p007_mixed_framed_traffic_glitches_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p007_mixed_framed_traffic_glitches_seq)

    function new(string name = "lvds_p007_mixed_framed_traffic_glitches_seq");
        super.new(name);
        case_id = "P007";
    endfunction
endclass
