// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e016_bitslip_walk_during_pll_relock_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e016_bitslip_walk_during_pll_relock_seq)

    function new(string name = "lvds_e016_bitslip_walk_during_pll_relock_seq");
        super.new(name);
        case_id = "E016";
    endfunction
endclass
