// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b034_phase_10_rollover_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b034_phase_10_rollover_seq)

    function new(string name = "lvds_b034_phase_10_rollover_seq");
        super.new(name);
        case_id = "B034";
    endfunction
endclass
