// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e025_butterfly_quarter_lane_outside_any_free_engine_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e025_butterfly_quarter_lane_outside_any_free_engine_seq)

    function new(string name = "lvds_e025_butterfly_quarter_lane_outside_any_free_engine_seq");
        super.new(name);
        case_id = "E025";
    endfunction
endclass
