// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p002_100k_symbols_1_glitch_on_all_lanes_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p002_100k_symbols_1_glitch_on_all_lanes_seq)

    function new(string name = "lvds_p002_100k_symbols_1_glitch_on_all_lanes_seq");
        super.new(name);
        case_id = "P002";
    endfunction
endclass
