// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x034_csr_access_at_non_existent_address_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x034_csr_access_at_non_existent_address_seq)

    function new(string name = "lvds_x034_csr_access_at_non_existent_address_seq");
        super.new(name);
        case_id = "X034";
    endfunction
endclass
