// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x032_score_accept_0_illegal_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x032_score_accept_0_illegal_seq)

    function new(string name = "lvds_x032_score_accept_0_illegal_seq");
        super.new(name);
        case_id = "X032";
    endfunction
endclass
