// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e019_n_engine_1_glitch_on_4_lanes_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e019_n_engine_1_glitch_on_4_lanes_seq)

    function new(string name = "lvds_e019_n_engine_1_glitch_on_4_lanes_seq");
        super.new(name);
        case_id = "E019";
    endfunction
endclass
