// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x018_redriver_losn_1_baseline_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x018_redriver_losn_1_baseline_seq)

    function new(string name = "lvds_x018_redriver_losn_1_baseline_seq");
        super.new(name);
        case_id = "X018";
    endfunction
endclass
