// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e006_score_tie_between_two_phases_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e006_score_tie_between_two_phases_seq)

    function new(string name = "lvds_e006_score_tie_between_two_phases_seq");
        super.new(name);
        case_id = "E006";
    endfunction
endclass
