// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x038_sva_avalon_mm_fires_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x038_sva_avalon_mm_fires_seq)

    function new(string name = "lvds_x038_sva_avalon_mm_fires_seq");
        super.new(name);
        case_id = "X038";
    endfunction
endclass
