// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b063_soft_resets_counts_requests_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b063_soft_resets_counts_requests_seq)

    function new(string name = "lvds_b063_soft_resets_counts_requests_seq");
        super.new(name);
        case_id = "B063";
    endfunction
endclass
