// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p031_random_glitch_class_per_cycle_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p031_random_glitch_class_per_cycle_seq)

    function new(string name = "lvds_p031_random_glitch_class_per_cycle_seq");
        super.new(name);
        case_id = "P031";
    endfunction
endclass
