// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x009_stuck_high_0x3ff_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x009_stuck_high_0x3ff_seq)

    function new(string name = "lvds_x009_stuck_high_0x3ff_seq");
        super.new(name);
        case_id = "X009";
    endfunction
endclass
