// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b027_data_reset_release_independent_of_control_reset_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b027_data_reset_release_independent_of_control_reset_seq)

    function new(string name = "lvds_b027_data_reset_release_independent_of_control_reset_seq");
        super.new(name);
        case_id = "B027";
    endfunction
endclass
