// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b036_4_lanes_all_phase_5_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b036_4_lanes_all_phase_5_seq)

    function new(string name = "lvds_b036_4_lanes_all_phase_5_seq");
        super.new(name);
        case_id = "B036";
    endfunction
endclass
