// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p001_100k_k28_5_idle_no_glitch_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p001_100k_k28_5_idle_no_glitch_seq)

    function new(string name = "lvds_p001_100k_k28_5_idle_no_glitch_seq");
        super.new(name);
        case_id = "P001";
    endfunction
endclass
