// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b010_sync_pattern_runtime_overwrite_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b010_sync_pattern_runtime_overwrite_seq)

    function new(string name = "lvds_b010_sync_pattern_runtime_overwrite_seq");
        super.new(name);
        case_id = "B010";
    endfunction
endclass
