// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x023_fiforst_handshake_never_completes_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x023_fiforst_handshake_never_completes_seq)

    function new(string name = "lvds_x023_fiforst_handshake_never_completes_seq");
        super.new(name);
        case_id = "X023";
    endfunction
endclass
