// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e014_bitslip_walk_on_attached_engine_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e014_bitslip_walk_on_attached_engine_seq)

    function new(string name = "lvds_e014_bitslip_walk_on_attached_engine_seq");
        super.new(name);
        case_id = "E014";
    endfunction
endclass
