// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b015_soft_reset_req_per_lane_self_clear_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b015_soft_reset_req_per_lane_self_clear_seq)

    function new(string name = "lvds_b015_soft_reset_req_per_lane_self_clear_seq");
        super.new(name);
        case_id = "B015";
    endfunction
endclass
