// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x002_soft_reset_during_steering_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x002_soft_reset_during_steering_seq)

    function new(string name = "lvds_x002_soft_reset_during_steering_seq");
        super.new(name);
        case_id = "X002";
    endfunction
endclass
