// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p003_100k_symbols_contention_sweep_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p003_100k_symbols_contention_sweep_seq)

    function new(string name = "lvds_p003_100k_symbols_contention_sweep_seq");
        super.new(name);
        case_id = "P003";
    endfunction
endclass
