// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b074_n_engine_2_n_lane_12_full_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b074_n_engine_2_n_lane_12_full_seq)

    function new(string name = "lvds_b074_n_engine_2_n_lane_12_full_seq");
        super.new(name);
        case_id = "B074";
    endfunction
endclass
