// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b018_mode_mask_auto_training_only_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b018_mode_mask_auto_training_only_seq)

    function new(string name = "lvds_b018_mode_mask_auto_training_only_seq");
        super.new(name);
        case_id = "B018";
    endfunction
endclass
