// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e008_alternating_accept_reject_crossing_threshold_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e008_alternating_accept_reject_crossing_threshold_seq)

    function new(string name = "lvds_e008_alternating_accept_reject_crossing_threshold_seq");
        super.new(name);
        case_id = "E008";
    endfunction
endclass
