// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p039_random_soft_reset_cadence_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p039_random_soft_reset_cadence_seq)

    function new(string name = "lvds_p039_random_soft_reset_cadence_seq");
        super.new(name);
        case_id = "P039";
    endfunction
endclass
