// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x006_self_clear_after_idle_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x006_self_clear_after_idle_seq)

    function new(string name = "lvds_x006_self_clear_after_idle_seq");
        super.new(name);
        case_id = "X006";
    endfunction
endclass
