// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b016_mode_mask_bit_slip_legacy_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b016_mode_mask_bit_slip_legacy_seq)

    function new(string name = "lvds_b016_mode_mask_bit_slip_legacy_seq");
        super.new(name);
        case_id = "B016";
    endfunction
endclass
