// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b030_phase_1_misalignment_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b030_phase_1_misalignment_seq)

    function new(string name = "lvds_b030_phase_1_misalignment_seq");
        super.new(name);
        case_id = "B030";
    endfunction
endclass
