// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e048_sync_pattern_with_wrong_rd_start_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e048_sync_pattern_with_wrong_rd_start_seq)

    function new(string name = "lvds_e048_sync_pattern_with_wrong_rd_start_seq");
        super.new(name);
        case_id = "E048";
    endfunction
endclass
