// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b020_score_reject_clamp_below_score_accept_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b020_score_reject_clamp_below_score_accept_seq)

    function new(string name = "lvds_b020_score_reject_clamp_below_score_accept_seq");
        super.new(name);
        case_id = "B020";
    endfunction
endclass
