// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p037_random_build_matrix_sweep_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p037_random_build_matrix_sweep_seq)

    function new(string name = "lvds_p037_random_build_matrix_sweep_seq");
        super.new(name);
        case_id = "P037";
    endfunction
endclass
