// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b062_engine_steerings_on_attach_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b062_engine_steerings_on_attach_seq)

    function new(string name = "lvds_b062_engine_steerings_on_attach_seq");
        super.new(name);
        case_id = "B062";
    endfunction
endclass
