// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x033_mode_mask_reserved_value_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x033_mode_mask_reserved_value_seq)

    function new(string name = "lvds_x033_mode_mask_reserved_value_seq");
        super.new(name);
        case_id = "X033";
    endfunction
endclass
