// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b054_lane_select_out_of_range_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b054_lane_select_out_of_range_seq)

    function new(string name = "lvds_b054_lane_select_out_of_range_seq");
        super.new(name);
        case_id = "B054";
    endfunction
endclass
