// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b007_meta_invalid_page_selector_holds_last_valid_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b007_meta_invalid_page_selector_holds_last_valid_seq)

    function new(string name = "lvds_b007_meta_invalid_page_selector_holds_last_valid_seq");
        super.new(name);
        case_id = "B007";
    endfunction
endclass
