// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b042_single_lane_engine_release_after_sustained_accept_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b042_single_lane_engine_release_after_sustained_accept_seq)

    function new(string name = "lvds_b042_single_lane_engine_release_after_sustained_accept_seq");
        super.new(name);
        case_id = "B042";
    endfunction
endclass
