// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x045_reset_asserted_during_csr_write_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x045_reset_asserted_during_csr_write_seq)

    function new(string name = "lvds_x045_reset_asserted_during_csr_write_seq");
        super.new(name);
        case_id = "X045";
    endfunction
endclass
