// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p023_bitslip_events_saturates_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p023_bitslip_events_saturates_seq)

    function new(string name = "lvds_p023_bitslip_events_saturates_seq");
        super.new(name);
        case_id = "P023";
    endfunction
endclass
