// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b011_lane_go_reset_value_all_on_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b011_lane_go_reset_value_all_on_seq)

    function new(string name = "lvds_b011_lane_go_reset_value_all_on_seq");
        super.new(name);
        case_id = "B011";
    endfunction
endclass
