// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b064_uptime_since_lock_advances_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b064_uptime_since_lock_advances_seq)

    function new(string name = "lvds_b064_uptime_since_lock_advances_seq");
        super.new(name);
        case_id = "B064";
    endfunction
endclass
