// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e037_back_to_back_csr_writes_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e037_back_to_back_csr_writes_seq)

    function new(string name = "lvds_e037_back_to_back_csr_writes_seq");
        super.new(name);
        case_id = "E037";
    endfunction
endclass
