// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b031_phase_2_misalignment_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b031_phase_2_misalignment_seq)

    function new(string name = "lvds_b031_phase_2_misalignment_seq");
        super.new(name);
        case_id = "B031";
    endfunction
endclass
