// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b021_coe_ctrl_pllrst_asserted_out_of_cold_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b021_coe_ctrl_pllrst_asserted_out_of_cold_seq)

    function new(string name = "lvds_b021_coe_ctrl_pllrst_asserted_out_of_cold_seq");
        super.new(name);
        case_id = "B021";
    endfunction
endclass
