// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x007_soft_reset_on_disabled_lane_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x007_soft_reset_on_disabled_lane_seq)

    function new(string name = "lvds_x007_soft_reset_on_disabled_lane_seq");
        super.new(name);
        case_id = "X007";
    endfunction
endclass
