// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p020_maximum_lane_count_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p020_maximum_lane_count_seq)

    function new(string name = "lvds_p020_maximum_lane_count_seq");
        super.new(name);
        case_id = "P020";
    endfunction
endclass
