// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e044_dpa_unlock_pulse_lane_2_vs_engine_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e044_dpa_unlock_pulse_lane_2_vs_engine_seq)

    function new(string name = "lvds_e044_dpa_unlock_pulse_lane_2_vs_engine_seq");
        super.new(name);
        case_id = "E044";
    endfunction
endclass
