// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b060_realigns_on_phase_change_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b060_realigns_on_phase_change_seq)

    function new(string name = "lvds_b060_realigns_on_phase_change_seq");
        super.new(name);
        case_id = "B060";
    endfunction
endclass
