// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x046_reset_asserted_during_avst_handshake_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x046_reset_asserted_during_avst_handshake_seq)

    function new(string name = "lvds_x046_reset_asserted_during_avst_handshake_seq");
        super.new(name);
        case_id = "X046";
    endfunction
endclass
