// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b052_lane_select_reset_default_0_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b052_lane_select_reset_default_0_seq)

    function new(string name = "lvds_b052_lane_select_reset_default_0_seq");
        super.new(name);
        case_id = "B052";
    endfunction
endclass
