// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e001_score_window_w_6_build_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e001_score_window_w_6_build_seq)

    function new(string name = "lvds_e001_score_window_w_6_build_seq");
        super.new(name);
        case_id = "E001";
    endfunction
endclass
