// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b080_engine_pool_full_occupancy_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b080_engine_pool_full_occupancy_seq)

    function new(string name = "lvds_b080_engine_pool_full_occupancy_seq");
        super.new(name);
        case_id = "B080";
    endfunction
endclass
