// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b050_mode_mask_auto_invokes_engine_only_on_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b050_mode_mask_auto_invokes_engine_only_on_seq)

    function new(string name = "lvds_b050_mode_mask_auto_invokes_engine_only_on_seq");
        super.new(name);
        case_id = "B050";
    endfunction
endclass
