// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e041_bitslip_walk_lane_0_vs_lane_1_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e041_bitslip_walk_lane_0_vs_lane_1_seq)

    function new(string name = "lvds_e041_bitslip_walk_lane_0_vs_lane_1_seq");
        super.new(name);
        case_id = "E041";
    endfunction
endclass
