// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b004_meta_page_1_returns_date_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b004_meta_page_1_returns_date_seq)

    function new(string name = "lvds_b004_meta_page_1_returns_date_seq");
        super.new(name);
        case_id = "B004";
    endfunction
endclass
