// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p030_pll_lock_churn_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p030_pll_lock_churn_seq)

    function new(string name = "lvds_p030_pll_lock_churn_seq");
        super.new(name);
        case_id = "P030";
    endfunction
endclass
