// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b003_meta_page_0_returns_version_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b003_meta_page_0_returns_version_seq)

    function new(string name = "lvds_b003_meta_page_0_returns_version_seq");
        super.new(name);
        case_id = "B003";
    endfunction
endclass
