// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x025_csr_write_while_soft_reset_req_in_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x025_csr_write_while_soft_reset_req_in_seq)

    function new(string name = "lvds_x025_csr_write_while_soft_reset_req_in_seq");
        super.new(name);
        case_id = "X025";
    endfunction
endclass
