// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x014_sparse_sync_k28_5_every_1024_symbols_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x014_sparse_sync_k28_5_every_1024_symbols_seq)

    function new(string name = "lvds_x014_sparse_sync_k28_5_every_1024_symbols_seq");
        super.new(name);
        case_id = "X014";
    endfunction
endclass
