// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e050_illegal_sync_pattern_all_zero_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e050_illegal_sync_pattern_all_zero_seq)

    function new(string name = "lvds_e050_illegal_sync_pattern_all_zero_seq");
        super.new(name);
        case_id = "E050";
    endfunction
endclass
