// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e049_sync_pattern_transient_change_during_traffic_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e049_sync_pattern_transient_change_during_traffic_seq)

    function new(string name = "lvds_e049_sync_pattern_transient_change_during_traffic_seq");
        super.new(name);
        case_id = "E049";
    endfunction
endclass
