// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p014_permanent_backpressure_on_one_lane_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p014_permanent_backpressure_on_one_lane_seq)

    function new(string name = "lvds_p014_permanent_backpressure_on_one_lane_seq");
        super.new(name);
        case_id = "P014";
    endfunction
endclass
