// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x020_pll_drops_lock_mid_traffic_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x020_pll_drops_lock_mid_traffic_seq)

    function new(string name = "lvds_x020_pll_drops_lock_mid_traffic_seq");
        super.new(name);
        case_id = "X020";
    endfunction
endclass
