// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x003_soft_reset_during_bitslip_walk_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x003_soft_reset_during_bitslip_walk_seq)

    function new(string name = "lvds_x003_soft_reset_during_bitslip_walk_seq");
        super.new(name);
        case_id = "X003";
    endfunction
endclass
