// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x036_sva_counter_sat_liveness_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x036_sva_counter_sat_liveness_seq)

    function new(string name = "lvds_x036_sva_counter_sat_liveness_seq");
        super.new(name);
        case_id = "X036";
    endfunction
endclass
