// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e003_score_accept_score_window_w_must_be_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e003_score_accept_score_window_w_must_be_seq)

    function new(string name = "lvds_e003_score_accept_score_window_w_must_be_seq");
        super.new(name);
        case_id = "E003";
    endfunction
endclass
