// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x012_bouncing_50_high_low_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x012_bouncing_50_high_low_seq)

    function new(string name = "lvds_x012_bouncing_50_high_low_seq");
        super.new(name);
        case_id = "X012";
    endfunction
endclass
