// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p012_50_random_backpressure_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p012_50_random_backpressure_seq)

    function new(string name = "lvds_p012_50_random_backpressure_seq");
        super.new(name);
        case_id = "P012";
    endfunction
endclass
