// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x030_dpa_hold_write_with_extra_bits_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x030_dpa_hold_write_with_extra_bits_seq)

    function new(string name = "lvds_x030_dpa_hold_write_with_extra_bits_seq");
        super.new(name);
        case_id = "X030";
    endfunction
endclass
