// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x037_sva_avalon_st_fires_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x037_sva_avalon_st_fires_seq)

    function new(string name = "lvds_x037_sva_avalon_st_fires_seq");
        super.new(name);
        case_id = "X037";
    endfunction
endclass
