// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e012_bitslip_walk_attempted_during_dpa_hold_1_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e012_bitslip_walk_attempted_during_dpa_hold_1_seq)

    function new(string name = "lvds_e012_bitslip_walk_attempted_during_dpa_hold_1_seq");
        super.new(name);
        case_id = "E012";
    endfunction
endclass
