// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e040_csr_access_above_maximum_address_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e040_csr_access_above_maximum_address_seq)

    function new(string name = "lvds_e040_csr_access_above_maximum_address_seq");
        super.new(name);
        case_id = "E040";
    endfunction
endclass
