// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b045_n_engine_n_lane_legacy_parity_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b045_n_engine_n_lane_legacy_parity_seq)

    function new(string name = "lvds_b045_n_engine_n_lane_legacy_parity_seq");
        super.new(name);
        case_id = "B045";
    endfunction
endclass
