// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e028_fabric_one_hot_exclusivity_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e028_fabric_one_hot_exclusivity_seq)

    function new(string name = "lvds_e028_fabric_one_hot_exclusivity_seq");
        super.new(name);
        case_id = "E028";
    endfunction
endclass
