// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x048_reset_asserted_during_bitslip_walk_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x048_reset_asserted_during_bitslip_walk_seq)

    function new(string name = "lvds_x048_reset_asserted_during_bitslip_walk_seq");
        super.new(name);
        case_id = "X048";
    endfunction
endclass
