// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e038_read_modify_write_of_mode_mask_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e038_read_modify_write_of_mode_mask_seq)

    function new(string name = "lvds_e038_read_modify_write_of_mode_mask_seq");
        super.new(name);
        case_id = "E038";
    endfunction
endclass
