// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x028_write_to_read_only_words_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x028_write_to_read_only_words_seq)

    function new(string name = "lvds_x028_write_to_read_only_words_seq");
        super.new(name);
        case_id = "X028";
    endfunction
endclass
