// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e011_bitslip_walk_off_10_pulses_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e011_bitslip_walk_off_10_pulses_seq)

    function new(string name = "lvds_e011_bitslip_walk_off_10_pulses_seq");
        super.new(name);
        case_id = "E011";
    endfunction
endclass
