// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e024_butterfly_half_lane_outside_reachable_subset_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e024_butterfly_half_lane_outside_reachable_subset_seq)

    function new(string name = "lvds_e024_butterfly_half_lane_outside_reachable_subset_seq");
        super.new(name);
        case_id = "E024";
    endfunction
endclass
