// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b001_read_uid_after_cold_reset_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b001_read_uid_after_cold_reset_seq)

    function new(string name = "lvds_b001_read_uid_after_cold_reset_seq");
        super.new(name);
        case_id = "B001";
    endfunction
endclass
