// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b008_capability_word_reports_compile_time_geometry_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b008_capability_word_reports_compile_time_geometry_seq)

    function new(string name = "lvds_b008_capability_word_reports_compile_time_geometry_seq");
        super.new(name);
        case_id = "B008";
    endfunction
endclass
