// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p025_checkpoint_growth_idle_soak_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p025_checkpoint_growth_idle_soak_seq)

    function new(string name = "lvds_p025_checkpoint_growth_idle_soak_seq");
        super.new(name);
        case_id = "P025";
    endfunction
endclass
