// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b046_lane_go_0_blocks_engine_attach_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b046_lane_go_0_blocks_engine_attach_seq)

    function new(string name = "lvds_b046_lane_go_0_blocks_engine_attach_seq");
        super.new(name);
        case_id = "B046";
    endfunction
endclass
