// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b009_sync_pattern_reset_value_is_k28_5_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b009_sync_pattern_reset_value_is_k28_5_seq)

    function new(string name = "lvds_b009_sync_pattern_reset_value_is_k28_5_seq");
        super.new(name);
        case_id = "B009";
    endfunction
endclass
