// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e035_reserved_csr_word_write_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e035_reserved_csr_word_write_seq)

    function new(string name = "lvds_e035_reserved_csr_word_write_seq");
        super.new(name);
        case_id = "E035";
    endfunction
endclass
