// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e030_lane_select_large_value_clamp_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e030_lane_select_large_value_clamp_seq)

    function new(string name = "lvds_e030_lane_select_large_value_clamp_seq");
        super.new(name);
        case_id = "E030";
    endfunction
endclass
