// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p028_periodic_counter_readback_during_idle_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p028_periodic_counter_readback_during_idle_seq)

    function new(string name = "lvds_p028_periodic_counter_readback_during_idle_seq");
        super.new(name);
        case_id = "P028";
    endfunction
endclass
