// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b040_loss_sync_pattern_cleared_after_lock_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b040_loss_sync_pattern_cleared_after_lock_seq)

    function new(string name = "lvds_b040_loss_sync_pattern_cleared_after_lock_seq");
        super.new(name);
        case_id = "B040";
    endfunction
endclass
