// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b038_n_lane_lanes_full_phase_sweep_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b038_n_lane_lanes_full_phase_sweep_seq)

    function new(string name = "lvds_b038_n_lane_lanes_full_phase_sweep_seq");
        super.new(name);
        case_id = "B038";
    endfunction
endclass
