// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b006_meta_page_3_returns_instance_id_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b006_meta_page_3_returns_instance_id_seq)

    function new(string name = "lvds_b006_meta_page_3_returns_instance_id_seq");
        super.new(name);
        case_id = "B006";
    endfunction
endclass
