// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e026_nearest_k_boundary_lane_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e026_nearest_k_boundary_lane_seq)

    function new(string name = "lvds_e026_nearest_k_boundary_lane_seq");
        super.new(name);
        case_id = "E026";
    endfunction
endclass
