// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x004_soft_reset_during_dpa_unlock_event_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x004_soft_reset_during_dpa_unlock_event_seq)

    function new(string name = "lvds_x004_soft_reset_during_dpa_unlock_event_seq");
        super.new(name);
        case_id = "X004";
    endfunction
endclass
