// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e004_score_accept_1_one_bit_accept_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e004_score_accept_1_one_bit_accept_seq)

    function new(string name = "lvds_e004_score_accept_1_one_bit_accept_seq");
        super.new(name);
        case_id = "E004";
    endfunction
endclass
