// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b041_single_lane_training_to_engine_attach_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b041_single_lane_training_to_engine_attach_seq)

    function new(string name = "lvds_b041_single_lane_training_to_engine_attach_seq");
        super.new(name);
        case_id = "B041";
    endfunction
endclass
