// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b075_n_engine_4_butterfly_half_reachability_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b075_n_engine_4_butterfly_half_reachability_seq)

    function new(string name = "lvds_b075_n_engine_4_butterfly_half_reachability_seq");
        super.new(name);
        case_id = "B075";
    endfunction
endclass
