// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x044_data_reset_deassert_before_control_reset_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x044_data_reset_deassert_before_control_reset_seq)

    function new(string name = "lvds_x044_data_reset_deassert_before_control_reset_seq");
        super.new(name);
        case_id = "X044";
    endfunction
endclass
