// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b019_score_accept_clamp_on_out_of_range_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b019_score_accept_clamp_on_out_of_range_seq)

    function new(string name = "lvds_b019_score_accept_clamp_on_out_of_range_seq");
        super.new(name);
        case_id = "B019";
    endfunction
endclass
