// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e042_glitch_on_lane_5_vs_lane_6_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e042_glitch_on_lane_5_vs_lane_6_seq)

    function new(string name = "lvds_e042_glitch_on_lane_5_vs_lane_6_seq");
        super.new(name);
        case_id = "E042";
    endfunction
endclass
