// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p009_random_sync_pattern_transient_changes_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p009_random_sync_pattern_transient_changes_seq)

    function new(string name = "lvds_p009_random_sync_pattern_transient_changes_seq");
        super.new(name);
        case_id = "P009";
    endfunction
endclass
