// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e013_back_to_back_bitslip_pulses_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e013_back_to_back_bitslip_pulses_seq)

    function new(string name = "lvds_e013_back_to_back_bitslip_pulses_seq");
        super.new(name);
        case_id = "E013";
    endfunction
endclass
