// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b035_inverted_starting_rd_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b035_inverted_starting_rd_seq)

    function new(string name = "lvds_b035_inverted_starting_rd_seq");
        super.new(name);
        case_id = "B035";
    endfunction
endclass
