// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b012_lane_go_clear_stops_one_lane_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b012_lane_go_clear_stops_one_lane_seq)

    function new(string name = "lvds_b012_lane_go_clear_stops_one_lane_seq");
        super.new(name);
        case_id = "B012";
    endfunction
endclass
