// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x015_dpalock_never_asserts_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x015_dpalock_never_asserts_seq)

    function new(string name = "lvds_x015_dpalock_never_asserts_seq");
        super.new(name);
        case_id = "X015";
    endfunction
endclass
