// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e047_sync_pattern_k23_7_lock_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e047_sync_pattern_k23_7_lock_seq)

    function new(string name = "lvds_e047_sync_pattern_k23_7_lock_seq");
        super.new(name);
        case_id = "E047";
    endfunction
endclass
