// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x024_spurious_rollover_without_bitslip_request_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x024_spurious_rollover_without_bitslip_request_seq)

    function new(string name = "lvds_x024_spurious_rollover_without_bitslip_request_seq");
        super.new(name);
        case_id = "X024";
    endfunction
endclass
