// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x043_control_reset_deassert_before_data_reset_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x043_control_reset_deassert_before_data_reset_seq)

    function new(string name = "lvds_x043_control_reset_deassert_before_data_reset_seq");
        super.new(name);
        case_id = "X043";
    endfunction
endclass
