// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b023_per_lane_dpa_lock_acquisition_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b023_per_lane_dpa_lock_acquisition_seq)

    function new(string name = "lvds_b023_per_lane_dpa_lock_acquisition_seq");
        super.new(name);
        case_id = "B023";
    endfunction
endclass
