// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p036_random_mode_mask_flips_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p036_random_mode_mask_flips_seq)

    function new(string name = "lvds_p036_random_mode_mask_flips_seq");
        super.new(name);
        case_id = "P036";
    endfunction
endclass
