// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b067_aperture_readback_equals_direct_csr_shadow_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b067_aperture_readback_equals_direct_csr_shadow_seq)

    function new(string name = "lvds_b067_aperture_readback_equals_direct_csr_shadow_seq");
        super.new(name);
        case_id = "B067";
    endfunction
endclass
