// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x031_lane_select_write_with_all_set_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x031_lane_select_write_with_all_set_seq)

    function new(string name = "lvds_x031_lane_select_write_with_all_set_seq");
        super.new(name);
        case_id = "X031";
    endfunction
endclass
