// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b058_bitslip_events_counts_pulses_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b058_bitslip_events_counts_pulses_seq)

    function new(string name = "lvds_b058_bitslip_events_counts_pulses_seq");
        super.new(name);
        case_id = "B058";
    endfunction
endclass
