// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b061_score_changes_on_engine_update_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b061_score_changes_on_engine_update_seq)

    function new(string name = "lvds_b061_score_changes_on_engine_update_seq");
        super.new(name);
        case_id = "B061";
    endfunction
endclass
