// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e043_soft_reset_lane_3_vs_lane_4_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e043_soft_reset_lane_3_vs_lane_4_seq)

    function new(string name = "lvds_e043_soft_reset_lane_3_vs_lane_4_seq");
        super.new(name);
        case_id = "E043";
    endfunction
endclass
