// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p006_worst_case_steering_latency_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p006_worst_case_steering_latency_seq)

    function new(string name = "lvds_p006_worst_case_steering_latency_seq");
        super.new(name);
        case_id = "P006";
    endfunction
endclass
