// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p008_100m_symbol_k28_5_line_rate_sustainment_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p008_100m_symbol_k28_5_line_rate_sustainment_seq)

    function new(string name = "lvds_p008_100m_symbol_k28_5_line_rate_sustainment_seq");
        super.new(name);
        case_id = "P008";
    endfunction
endclass
