// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x011_stuck_on_one_valid_non_k28_5_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x011_stuck_on_one_valid_non_k28_5_seq)

    function new(string name = "lvds_x011_stuck_on_one_valid_non_k28_5_seq");
        super.new(name);
        case_id = "X011";
    endfunction
endclass
