// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e005_score_reject_0_always_rejects_below_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e005_score_reject_0_always_rejects_below_seq)

    function new(string name = "lvds_e005_score_reject_0_always_rejects_below_seq");
        super.new(name);
        case_id = "E005";
    endfunction
endclass
