// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b065_uptime_since_lock_resets_on_comma_loss_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b065_uptime_since_lock_resets_on_comma_loss_seq)

    function new(string name = "lvds_b065_uptime_since_lock_resets_on_comma_loss_seq");
        super.new(name);
        case_id = "B065";
    endfunction
endclass
