// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x005_all_lanes_soft_reset_simultaneously_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x005_all_lanes_soft_reset_simultaneously_seq)

    function new(string name = "lvds_x005_all_lanes_soft_reset_simultaneously_seq");
        super.new(name);
        case_id = "X005";
    endfunction
endclass
