// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b073_n_engine_n_lane_full_xbar_legacy_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b073_n_engine_n_lane_full_xbar_legacy_seq)

    function new(string name = "lvds_b073_n_engine_n_lane_full_xbar_legacy_seq");
        super.new(name);
        case_id = "B073";
    endfunction
endclass
