// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e017_rollover_at_non_multiple_of_10_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e017_rollover_at_non_multiple_of_10_seq)

    function new(string name = "lvds_e017_rollover_at_non_multiple_of_10_seq");
        super.new(name);
        case_id = "E017";
    endfunction
endclass
