// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x042_both_resets_asserted_then_released_same_cycle_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x042_both_resets_asserted_then_released_same_cycle_seq)

    function new(string name = "lvds_x042_both_resets_asserted_then_released_same_cycle_seq");
        super.new(name);
        case_id = "X042";
    endfunction
endclass
