// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p033_random_engine_attach_delay_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p033_random_engine_attach_delay_seq)

    function new(string name = "lvds_p033_random_engine_attach_delay_seq");
        super.new(name);
        case_id = "P033";
    endfunction
endclass
