// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b014_dpa_hold_per_lane_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b014_dpa_hold_per_lane_seq)

    function new(string name = "lvds_b014_dpa_hold_per_lane_seq");
        super.new(name);
        case_id = "B014";
    endfunction
endclass
