// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x019_continuous_bitslip_churn_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x019_continuous_bitslip_churn_seq)

    function new(string name = "lvds_x019_continuous_bitslip_churn_seq");
        super.new(name);
        case_id = "X019";
    endfunction
endclass
