// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e023_engine_attached_lane_goes_idle_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e023_engine_attached_lane_goes_idle_seq)

    function new(string name = "lvds_e023_engine_attached_lane_goes_idle_seq");
        super.new(name);
        case_id = "E023";
    endfunction
endclass
