// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x021_dpalock_asserts_then_drops_every_100_cycles_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x021_dpalock_asserts_then_drops_every_100_cycles_seq)

    function new(string name = "lvds_x021_dpalock_asserts_then_drops_every_100_cycles_seq");
        super.new(name);
        case_id = "X021";
    endfunction
endclass
