// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b044_n_engine_4_two_lanes_simultaneously_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b044_n_engine_4_two_lanes_simultaneously_seq)

    function new(string name = "lvds_b044_n_engine_4_two_lanes_simultaneously_seq");
        super.new(name);
        case_id = "B044";
    endfunction
endclass
