// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p027_no_phantom_engine_steerings_under_idle_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p027_no_phantom_engine_steerings_under_idle_seq)

    function new(string name = "lvds_p027_no_phantom_engine_steerings_under_idle_seq");
        super.new(name);
        case_id = "P027";
    endfunction
endclass
