// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b028_cold_reset_returns_ip_to_defaults_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b028_cold_reset_returns_ip_to_defaults_seq)

    function new(string name = "lvds_b028_cold_reset_returns_ip_to_defaults_seq");
        super.new(name);
        case_id = "B028";
    endfunction
endclass
