// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b039_loss_sync_pattern_asserted_during_walk_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b039_loss_sync_pattern_asserted_during_walk_seq)

    function new(string name = "lvds_b039_loss_sync_pattern_asserted_during_walk_seq");
        super.new(name);
        case_id = "B039";
    endfunction
endclass
