// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b029_already_aligned_phase_0_k28_5_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b029_already_aligned_phase_0_k28_5_seq)

    function new(string name = "lvds_b029_already_aligned_phase_0_k28_5_seq");
        super.new(name);
        case_id = "B029";
    endfunction
endclass
