// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b024_fifo_reset_issued_after_dpa_lock_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b024_fifo_reset_issued_after_dpa_lock_seq)

    function new(string name = "lvds_b024_fifo_reset_issued_after_dpa_lock_seq");
        super.new(name);
        case_id = "B024";
    endfunction
endclass
