// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b051_lane_select_atomic_over_10_reads_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b051_lane_select_atomic_over_10_reads_seq)

    function new(string name = "lvds_b051_lane_select_atomic_over_10_reads_seq");
        super.new(name);
        case_id = "B051";
    endfunction
endclass
