// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p025_10g_symbol_soak_24h_sim_equivalent_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p025_10g_symbol_soak_24h_sim_equivalent_seq)

    function new(string name = "lvds_p025_10g_symbol_soak_24h_sim_equivalent_seq");
        super.new(name);
        case_id = "P025";
    endfunction
endclass
