// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b047_dpa_hold_defers_training_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b047_dpa_hold_defers_training_seq)

    function new(string name = "lvds_b047_dpa_hold_defers_training_seq");
        super.new(name);
        case_id = "B047";
    endfunction
endclass
