// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e015_walk_on_lane_0_while_lane_1_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e015_walk_on_lane_0_while_lane_1_seq)

    function new(string name = "lvds_e015_walk_on_lane_0_while_lane_1_seq");
        super.new(name);
        case_id = "E015";
    endfunction
endclass
