// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p017_throughput_with_periodic_dpa_unlock_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p017_throughput_with_periodic_dpa_unlock_seq)

    function new(string name = "lvds_p017_throughput_with_periodic_dpa_unlock_seq");
        super.new(name);
        case_id = "P017";
    endfunction
endclass
