// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p018_throughput_with_sync_pattern_flips_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p018_throughput_with_sync_pattern_flips_seq)

    function new(string name = "lvds_p018_throughput_with_sync_pattern_flips_seq");
        super.new(name);
        case_id = "P018";
    endfunction
endclass
