// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b072_n_engine_1_legacy_parity_falsifier_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b072_n_engine_1_legacy_parity_falsifier_seq)

    function new(string name = "lvds_b072_n_engine_1_legacy_parity_falsifier_seq");
        super.new(name);
        case_id = "B072";
    endfunction
endclass
