// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_p032_random_lane_targeting_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_p032_random_lane_targeting_seq)

    function new(string name = "lvds_p032_random_lane_targeting_seq");
        super.new(name);
        case_id = "P032";
    endfunction
endclass
