// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b049_mode_mask_adaptive_invokes_engine_eagerly_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b049_mode_mask_adaptive_invokes_engine_eagerly_seq)

    function new(string name = "lvds_b049_mode_mask_adaptive_invokes_engine_eagerly_seq");
        super.new(name);
        case_id = "B049";
    endfunction
endclass
