// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b002_write_to_uid_is_silently_ignored_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b002_write_to_uid_is_silently_ignored_seq)

    function new(string name = "lvds_b002_write_to_uid_is_silently_ignored_seq");
        super.new(name);
        case_id = "B002";
    endfunction
endclass
