// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b066_two_counters_increment_same_cycle_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b066_two_counters_increment_same_cycle_seq)

    function new(string name = "lvds_b066_two_counters_increment_same_cycle_seq");
        super.new(name);
        case_id = "B066";
    endfunction
endclass
