// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e031_concurrent_counter_increment_during_aperture_read_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e031_concurrent_counter_increment_during_aperture_read_seq)

    function new(string name = "lvds_e031_concurrent_counter_increment_during_aperture_read_seq");
        super.new(name);
        case_id = "E031";
    endfunction
endclass
