// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b048_mode_mask_bit_slip_never_invokes_engine_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b048_mode_mask_bit_slip_never_invokes_engine_seq)

    function new(string name = "lvds_b048_mode_mask_bit_slip_never_invokes_engine_seq");
        super.new(name);
        case_id = "B048";
    endfunction
endclass
