// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e036_csr_write_while_soft_reset_req_0_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e036_csr_write_while_soft_reset_req_0_seq)

    function new(string name = "lvds_e036_csr_write_while_soft_reset_req_0_seq");
        super.new(name);
        case_id = "E036";
    endfunction
endclass
