// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_b059_dpa_unlocks_on_dpalock_falling_edge_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_b059_dpa_unlocks_on_dpalock_falling_edge_seq)

    function new(string name = "lvds_b059_dpa_unlocks_on_dpalock_falling_edge_seq");
        super.new(name);
        case_id = "B059";
    endfunction
endclass
