// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_x010_stuck_low_0x000_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_x010_stuck_low_0x000_seq)

    function new(string name = "lvds_x010_stuck_low_0x000_seq");
        super.new(name);
        case_id = "X010";
    endfunction
endclass
