// Generated by tb/uvm/script/generate_case_sequences.py; do not hand-edit.
class lvds_e010_perfect_100_score_window_seq extends lvds_case_sequence_base;
    `uvm_object_utils(lvds_e010_perfect_100_score_window_seq)

    function new(string name = "lvds_e010_perfect_100_score_window_seq");
        super.new(name);
        case_id = "E010";
    endfunction
endclass
